// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPP.Core.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerTimeTrial : EntityBase
    {
        public int Assessment { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Name { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public string DominantSkill { get; set; }
        public string CurrentState { get; set; }
        public Nullable<int> C2kmTimeTrial_min { get; set; }
        public Nullable<int> C2kmTimeTrial_sec { get; set; }
        public Nullable<decimal> AveragePace_mps { get; set; }
        public Nullable<decimal> AveragePace_kph { get; set; }
        public Nullable<bool> isTestedIndoors { get; set; }
        public Nullable<bool> isTestedOutdoors { get; set; }
        public Nullable<bool> isEnduranceInjured { get; set; }
        public Nullable<int> C2kmTimeTrialSecConverted { get; set; }
        public Nullable<int> C2kmTimeTrialMinConverted { get; set; }
        public Nullable<int> SortTotalSeconds { get; set; }
        public Nullable<int> C2kmTimeTrialTotalSeconds { get; set; }
        public Nullable<int> C2kmTimeTrialTotalMinutes { get; set; }
        public Nullable<int> TotalSeconds { get; set; }
        public string TimeAsText { get; set; }
        public Nullable<decimal> TotalMinutes { get; set; }
    }
}
