// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPP.Core.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerRating : EntityBase
    {
        public int PlayerId { get; set; }
        public System.DateTime RatingDate { get; set; }
        public string Format { get; set; }
        public Nullable<int> BattingNow { get; set; }
        public Nullable<int> BattingProjected { get; set; }
        public Nullable<int> BowlingNow { get; set; }
        public Nullable<int> BowlingProjected { get; set; }
        public Nullable<int> FieldingNow { get; set; }
        public Nullable<int> FieldingProjected { get; set; }
        public Nullable<int> WicketKeepingNow { get; set; }
        public Nullable<int> WicketKeepingProjected { get; set; }
        public Nullable<int> Character { get; set; }
    }
}
